### ISSUE TITLE
What's the data's form here?

### ISSUE THREAD

**Issue by stupidstupidstupidstupid** [BiomedicalMachineLearning/Medulloblastoma#3]
It seems that I need a filtered matrix to input in R. 
But I can only get fastq data in the article without code to deal with it.
Can you provide some advice on this problem? Thanks in advance.

**Comment by Shikari666** [comment]
Hey guys

Good Afternoon!
Can we get the spatial data as we can only see tiff files when we check the data availability from your paper  and it would be really helpful if I can get .h5 file or a seurat object(that contains spatial info)

-R
